#!/bin/bash

# Actualiza el sistema
sudo apt update && sudo apt upgrade -y

# Instala Apache
sudo apt install apache2 -y

# Instala PHP y módulos adicionales
sudo apt install php libapache2-mod-php php-mysql -y

# Habilita el módulo de PHP en Apache
sudo a2enmod php

# Habilita Apache para que se inicie al arrancar el sistema
sudo systemctl enable apache2

# Reinicia Apache para aplicar los cambios
sudo systemctl restart apache2

# Muestra el estado de Apache
sudo systemctl status apache2

echo "Apache y PHP se han instalado correctamente y Apache se iniciará automáticamente al reiniciar."
